import { TheHeader } from "@/components/TheHeader";
import "../app/globals.css";
import type { Metadata } from "next";
import { TheFooter } from "@/components/TheFooter";
import { Providers } from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TheHeader />
          <main className="section">{children}</main>
          <TheFooter />
        </Providers>
      </body>
    </html>
  );
}
